### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [bob-reus/edgar-saltus_the-truth-about-tristrem-varick#1]
### dedication.xhtml:

- [x] The text needs to be changed to the correct case. You can add `<b>` and style it with `text-transform: uppercase;`.

- [x] `<p>New York, <time datetime="1888-02-15">15th February, 1888</time></p>` need to be in a `<footer>`.

### chapter-1.xhtml:

- [x] For `<i>Well done, Weldon</i>`, convert `<i>` into `<em>`.

### chapter-2.xhtml:

- [x] `<span epub:type="se:name.music.song" xml:lang="it">Non più mesta</span>` can be italicized since it is in Italian.

### chapter-4.xhtml:

- [x] `<span epub:type="se:name.music.song" xml:lang="it">Il segreto per esser felice</span>` can be italicized since it is in Italian.

### chapter-5.xhtml:

- [x] For `<i>Well done, Weldon</i>`, convert `<i>` into `<em>`.

### chapter-9.xhtml:

- [x] "obiter dicta" is in MW and doesn't need italics.

- [x] "in banco" is in MW and doesn't need italics.

- [x] "prima facie" is in MW and doesn't need italics.

### chapter-12.xhtml:

- [x] Remove `epub:type="z3998:persona"`. We reserve this for play formatting.

- [x] The single quote in `’Aimer est le grand point` is in the wrong direction.

### toc.xhtml:

- [x] Re-run `se build-toc .` and commit the changes.

**Comment by bob-reus** [comment]
**Chapter-9.xhtml:** Shouldn´t _in banco_ be italicized, as described in [SEMoS 8.2.9.9](https://standardebooks.org/manual/1.7.0/single-page#8.2.9.9)? I'll revert the others. 

**Chapter-12.xhtml, epub:type="z3998:persona":** This has been done before though, I used https://github.com/standardebooks/edwin-a-abbott_flatland/blob/master/src/epub/text/chapter-14.xhtml as an example.

**dedication.xhtml:** Lint returns `<footer> missing margin-top: 1em; text-align: <value>;. text-align is usually set to right.` even after I added the styling to local.css. Should I add it to se-lint-ignore.xml?

**Comment by EmmaSweeney** [comment]
> Chapter-9.xhtml: Shouldn´t in banco be italicized, as described in [SEMoS 8.2.9.9](https://standardebooks.org/manual/1.7.0/single-page#8.2.9.9)? I'll revert the others.

If you think that this phrase could be confusing, then you can keep it italicized.

> Chapter-12.xhtml, epub:type="z3998:persona": This has been done before though, I used https://github.com/standardebooks/edwin-a-abbott_flatland/blob/master/src/epub/text/chapter-14.xhtml as an example.

To my knowledge, `epub:type="z3998:persona"` is used only for play and drama formatting. @acabal, Is this correct?

> dedication.xhtml: Lint returns `<footer> missing margin-top: 1em; text-align: <value>;. text-align is usually set to right.` even after I added the styling to local.css. Should I add it to se-lint-ignore.xml?

Use the following CSS:
```
section[epub|type~="dedication"] > footer{
	margin-top: 1em;
	text-align: initial;
}
```

**Comment by acabal** [comment]
> To my knowledge, epub:type="z3998:persona" is used only for play and drama formatting. @acabal, Is this correct?

We can use it in these cases where there's play-like dialogue in the text calling for offsetting the speakers somehow.

**Comment by bob-reus** [comment]
> Use the following CSS:
> 
> ```
> section[epub|type~="dedication"] > footer{
> 	margin-top: 1em;
> 	text-align: initial;
> }
> ```

Alright, I changed this in a rebase. 

With that, all issues have been resolved. Thank you both! :)
