### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [bob-reus/edgar-saltus_the-truth-about-tristrem-varick#2]
- [x] Remove `epub:type="se:name.music.song"` from `<i epub:type="se:name.music.song" xml:lang="it">`. Lint will no longer complain.

- [x] The flex display CSS for the dedication can be combined.

**Comment by bob-reus** [comment]
I moved the semantics to a span wrapping the quotes like this: `<span epub:type="se:name.music.song">“<i xml:lang="it">Non più mesta</i>,”</span>` to keep the semantics intact. I hope this works :)
